apiVersion: v1
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
data:
    activemq.xml: {{ tpl (.Files.Get "conf/activemq.xml") . | b64enc }}
    jetty.xml: {{ tpl (.Files.Get "conf/jetty.xml") .  | b64enc }}   
