apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app.kubernetes.io/name: activemq
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: console
      port: 8161
    - protocol: TCP
      name: openwire
      port: 50900
      targetPort: 61616
    - protocol: TCP
      name: jmx
      port: 50901
      targetPort: 50901
    - protocol: TCP
      name: sftp
      port: 22

