apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: apache/activemq-classic:6.1.4
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pkill -f activemq"]
        resources:
          requests:
              memory: 1Gi
              cpu: 1
          limits:
              memory: 1Gi
              cpu: 1
        ports:
          - containerPort: 8161
          - containerPort: 61613
          - containerPort: 61616
        volumeMounts:
        - name: data
          mountPath: /opt/apache-activemq/data
        - name: activemq-xml
          mountPath: /opt/apache-activemq/conf/activemq.xml
          subPath: activemq.xml
        - name: jetty-xml
          mountPath: /opt/apache-activemq/conf/jetty.xml
          subPath: jetty.xml
      volumes:
      - name: activemq-xml
        secret:
          secretName: {{ .Release.Name }}-config
      - name: jetty-xml
        secret:
          secretName: {{ .Release.Name }}-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi